# https://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 10
      MSYSTEM: MINGW64
      BASH_PATH: C:\msys64\usr\bin\bash

clone_depth: 10

version: "{build}"
build: off
deploy: off

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@latest
  - npm install

cache:
  - node_modules

test_script:
  - node --version
  - npm --version
  - npm run test-only
